apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ch-dev
nameSuffix: -dev
resources:
  - ../../base
patches:
  - target:
      kind: BuildConfig
      name: canhappy
    patch: |-
      - op: replace
        path: /spec/source/git/ref
        value: feature/CH-OS-V1
  - target:
      kind: ConfigMap
      name: canhappy-env
    patch: |-
      - op: replace
        path: /data/ASPNETCORE_ENVIRONMENT
        value: OpenShift.Development
      - op: replace
        path: /data/EnableDebug
        value: "true"
  - target:
      kind: Deployment
      name: canhappy
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/1/secretRef/name
        value: canhappy-secrets-dev
  - target:
      kind: Route
      name: canhappy
    patch: |-
      - op: add
        path: /spec/host
        value: canhappy-dev.apps-crc.testing
